apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_app
  template:
    metadata:
      labels:
        app: nginx_app
    spec:
      containers:
      - name: nginx_app
        image: webserver
        ports:
        - containerPort: 80